build:
  version: 2016-03-14
  steps:
    builder:
      name: builder
      dockerfile: Dockerfile
      no_cache: true
      secrets:
        really_really_secret_stuff:
          type: env
          value: REALLY_REALLY_SECRET_STUFF
