services:
  clean_deployment:
    use_habitus: true
    use_habitus_step: deployment
    habitus_filename: clean_build.yml
    git_url: https://github.com/cloud66-samples/habitus-builds.git
    git_branch: test-multiple-build-files
  dirty_deployment:
    use_habitus: true
    use_habitus_step: deployment
    habitus_filename: dirty_build.yml
    git_url: https://github.com/cloud66-samples/habitus-builds.git
    git_branch: test-multiple-build-files
databases: []
version: 2
